spring:
  application:
    name: Spring-Reactive
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/spring_reactive
    username: postgres
    password: password1234
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/spring_reactive
    user: postgres
    password: password1234
    baseline-on-migrate: true
